# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: interchange.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='interchange.proto',
  package='interchange',
  syntax='proto3',
  serialized_pb=_b('\n\x11interchange.proto\x12\x0binterchange\"\x17\n\x08ObjectID\x12\x0b\n\x03_id\x18\x01 \x01(\t\"\x17\n\x07Package\x12\x0c\n\x04name\x18\x01 \x01(\t2W\n\x12InterchangeService\x12\x41\n\x0eStreamPackages\x12\x15.interchange.ObjectID\x1a\x14.interchange.Package\"\x00\x30\x01\x42(\n\x11me.nevi.grpc-demoB\x11InterchangeProtosH\x01\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_OBJECTID = _descriptor.Descriptor(
  name='ObjectID',
  full_name='interchange.ObjectID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='_id', full_name='interchange.ObjectID._id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=57,
)


_PACKAGE = _descriptor.Descriptor(
  name='Package',
  full_name='interchange.Package',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='interchange.Package.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=82,
)

DESCRIPTOR.message_types_by_name['ObjectID'] = _OBJECTID
DESCRIPTOR.message_types_by_name['Package'] = _PACKAGE

ObjectID = _reflection.GeneratedProtocolMessageType('ObjectID', (_message.Message,), dict(
  DESCRIPTOR = _OBJECTID,
  __module__ = 'interchange_pb2'
  # @@protoc_insertion_point(class_scope:interchange.ObjectID)
  ))
_sym_db.RegisterMessage(ObjectID)

Package = _reflection.GeneratedProtocolMessageType('Package', (_message.Message,), dict(
  DESCRIPTOR = _PACKAGE,
  __module__ = 'interchange_pb2'
  # @@protoc_insertion_point(class_scope:interchange.Package)
  ))
_sym_db.RegisterMessage(Package)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\021me.nevi.grpc-demoB\021InterchangeProtosH\001'))
try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces


  class InterchangeServiceStub(object):

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.StreamPackages = channel.unary_stream(
          '/interchange.InterchangeService/StreamPackages',
          request_serializer=ObjectID.SerializeToString,
          response_deserializer=Package.FromString,
          )


  class InterchangeServiceServicer(object):

    def StreamPackages(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_InterchangeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'StreamPackages': grpc.unary_stream_rpc_method_handler(
            servicer.StreamPackages,
            request_deserializer=ObjectID.FromString,
            response_serializer=Package.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'interchange.InterchangeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaInterchangeServiceServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def StreamPackages(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaInterchangeServiceStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def StreamPackages(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()


  def beta_create_InterchangeService_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('interchange.InterchangeService', 'StreamPackages'): ObjectID.FromString,
    }
    response_serializers = {
      ('interchange.InterchangeService', 'StreamPackages'): Package.SerializeToString,
    }
    method_implementations = {
      ('interchange.InterchangeService', 'StreamPackages'): face_utilities.unary_stream_inline(servicer.StreamPackages),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_InterchangeService_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('interchange.InterchangeService', 'StreamPackages'): ObjectID.SerializeToString,
    }
    response_deserializers = {
      ('interchange.InterchangeService', 'StreamPackages'): Package.FromString,
    }
    cardinalities = {
      'StreamPackages': cardinality.Cardinality.UNARY_STREAM,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'interchange.InterchangeService', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
